services:
  - type: web
    name: techknots-meet
    env: node
    rootDir: server
    buildCommand: cd ../client && npm install && npm run build && cd ../server && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: CLIENT_ORIGIN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MEDIASOUP_LISTEN_IP
        value: 0.0.0.0
      - key: MEDIASOUP_ANNOUNCED_IP
        value: auto
      - key: MEDIASOUP_MIN_PORT
        value: 40000
      - key: MEDIASOUP_MAX_PORT
        value: 49999

